### ISSUE TITLE
Feature Request: Support Cronjob-like Scheduling for Updates

### ISSUE THREAD

**Issue by chaos-baum** [NewAmazingPVP/AutoViaUpdater#7]
Hi,

First of all, thank you for your fantastic work on **autoviaupdater**. It has been incredibly helpful!

**Feature Request:**

Currently, the updater allows setting update intervals in minutes. It would be a great enhancement to support scheduling updates using a cronjob-like format. This feature would provide more flexibility, enabling users to specify updates at exact times or on specific days.

**Benefits:**

- **Flexibility:** Schedule updates during off-peak hours or at specific times.
- **Precision:** Target updates to run on particular days of the week or month.
- **Familiarity:** Many users are accustomed to cron syntax, making it an intuitive option.

**Example Usage:**

Allow users to specify a cron expression, such as:

- `0 2 * * *` – Every day at 2 AM
- `*/15 * * * *` – Every 15 minutes
- `0 0 * * 0` – Every Sunday at midnight

**Possible Implementation:**

- Integrate a cron parsing library to interpret the expressions.
- Add validation to handle incorrect syntax.
- Update the documentation with examples and guidelines.

**Conclusion:**

Implementing cronjob-like scheduling would make **autoviaupdater** even more versatile and user-friendly. Thank you for considering this feature!

**Comment by NewAmazingPVP** [comment]
@Ceddicedced Sure, on my TODO list! Will work on it when I get time to.

**Comment by NewAmazingPVP** [comment]
Hey @Ceddicedced, sorry for taking a while. Please test this [build](https://cdn.discordapp.com/attachments/1312252725626408991/1312252741380341780/AutoViaUpdater-experimentalCronSupport.jar?ex=674bd21a&is=674a809a&hm=3f394f6f0c2abc845ad7d604feb6d3f64feb2b214baceb77cb4667639828372d&) and let me know if it functions as intended. You will have to regenerate the config to see the cron expression section.

**Comment by NewAmazingPVP** [comment]
Added in v9.5 please let me know how it goes!
